#pragma once
#include <ntddk.h>

#define DEVICE_TYPE1 0x8000
#define IOCTL_CHECK_PROCESS CTL_CODE(DEVICE_TYPE1, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SEND_RESULT  CTL_CODE(DEVICE_TYPE1, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _USER_PROCESS_ITEM {
	ULONG ProcessId;
	WCHAR ImageFileName[260];
	BOOLEAN AllowProcess; 
}USER_PROCESS_ITEM, *PUSER_PROCESS_ITEM;